genre_table = {0: 'Romance',
               1: 'Mystery',
               2: 'Science Fiction',
               3: 'Thriller',
               4: 'Young Adult',
               5: 'Children’s Fiction',
               6: 'Self-help',
               7: 'Fantasy',
               8: 'Historical Fiction',
               9: 'Poetry'}